//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("practicam6Model", "factura_ibfk_1", "clients", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Practica_M06.clients), "factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Practica_M06.factura), true)]

#endregion

namespace Practica_M06
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class practicam6Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto practicam6Entities usando la cadena de conexión encontrada en la sección 'practicam6Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public practicam6Entities() : base("name=practicam6Entities", "practicam6Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto practicam6Entities.
        /// </summary>
        public practicam6Entities(string connectionString) : base(connectionString, "practicam6Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto practicam6Entities.
        /// </summary>
        public practicam6Entities(EntityConnection connection) : base(connection, "practicam6Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<clients> clients
        {
            get
            {
                if ((_clients == null))
                {
                    _clients = base.CreateObjectSet<clients>("clients");
                }
                return _clients;
            }
        }
        private ObjectSet<clients> _clients;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<factura> factura
        {
            get
            {
                if ((_factura == null))
                {
                    _factura = base.CreateObjectSet<factura>("factura");
                }
                return _factura;
            }
        }
        private ObjectSet<factura> _factura;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<factura_detall> factura_detall
        {
            get
            {
                if ((_factura_detall == null))
                {
                    _factura_detall = base.CreateObjectSet<factura_detall>("factura_detall");
                }
                return _factura_detall;
            }
        }
        private ObjectSet<factura_detall> _factura_detall;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<productes> productes
        {
            get
            {
                if ((_productes == null))
                {
                    _productes = base.CreateObjectSet<productes>("productes");
                }
                return _productes;
            }
        }
        private ObjectSet<productes> _productes;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clients. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclients(clients clients)
        {
            base.AddObject("clients", clients);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet factura. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTofactura(factura factura)
        {
            base.AddObject("factura", factura);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet factura_detall. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTofactura_detall(factura_detall factura_detall)
        {
            base.AddObject("factura_detall", factura_detall);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet productes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproductes(productes productes)
        {
            base.AddObject("productes", productes);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="practicam6Model", Name="clients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clients : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto clients.
        /// </summary>
        /// <param name="id_Client">Valor inicial de la propiedad id_Client.</param>
        /// <param name="nom">Valor inicial de la propiedad Nom.</param>
        /// <param name="cognom1">Valor inicial de la propiedad Cognom1.</param>
        /// <param name="adreça">Valor inicial de la propiedad Adreça.</param>
        /// <param name="codi_Postal">Valor inicial de la propiedad Codi_Postal.</param>
        /// <param name="població">Valor inicial de la propiedad Població.</param>
        /// <param name="província">Valor inicial de la propiedad Província.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        public static clients Createclients(global::System.Int32 id_Client, global::System.String nom, global::System.String cognom1, global::System.String adreça, global::System.Int32 codi_Postal, global::System.String població, global::System.String província, global::System.String email)
        {
            clients clients = new clients();
            clients.id_Client = id_Client;
            clients.Nom = nom;
            clients.Cognom1 = cognom1;
            clients.Adreça = adreça;
            clients.Codi_Postal = codi_Postal;
            clients.Població = població;
            clients.Província = província;
            clients.Email = email;
            return clients;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Client
        {
            get
            {
                return _id_Client;
            }
            set
            {
                if (_id_Client != value)
                {
                    Onid_ClientChanging(value);
                    ReportPropertyChanging("id_Client");
                    _id_Client = StructuralObject.SetValidValue(value, "id_Client");
                    ReportPropertyChanged("id_Client");
                    Onid_ClientChanged();
                }
            }
        }
        private global::System.Int32 _id_Client;
        partial void Onid_ClientChanging(global::System.Int32 value);
        partial void Onid_ClientChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false, "Nom");
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cognom1
        {
            get
            {
                return _Cognom1;
            }
            set
            {
                OnCognom1Changing(value);
                ReportPropertyChanging("Cognom1");
                _Cognom1 = StructuralObject.SetValidValue(value, false, "Cognom1");
                ReportPropertyChanged("Cognom1");
                OnCognom1Changed();
            }
        }
        private global::System.String _Cognom1;
        partial void OnCognom1Changing(global::System.String value);
        partial void OnCognom1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cognom2
        {
            get
            {
                return _Cognom2;
            }
            set
            {
                OnCognom2Changing(value);
                ReportPropertyChanging("Cognom2");
                _Cognom2 = StructuralObject.SetValidValue(value, true, "Cognom2");
                ReportPropertyChanged("Cognom2");
                OnCognom2Changed();
            }
        }
        private global::System.String _Cognom2;
        partial void OnCognom2Changing(global::System.String value);
        partial void OnCognom2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adreça
        {
            get
            {
                return _Adreça;
            }
            set
            {
                OnAdreçaChanging(value);
                ReportPropertyChanging("Adreça");
                _Adreça = StructuralObject.SetValidValue(value, false, "Adreça");
                ReportPropertyChanged("Adreça");
                OnAdreçaChanged();
            }
        }
        private global::System.String _Adreça;
        partial void OnAdreçaChanging(global::System.String value);
        partial void OnAdreçaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codi_Postal
        {
            get
            {
                return _Codi_Postal;
            }
            set
            {
                OnCodi_PostalChanging(value);
                ReportPropertyChanging("Codi_Postal");
                _Codi_Postal = StructuralObject.SetValidValue(value, "Codi_Postal");
                ReportPropertyChanged("Codi_Postal");
                OnCodi_PostalChanged();
            }
        }
        private global::System.Int32 _Codi_Postal;
        partial void OnCodi_PostalChanging(global::System.Int32 value);
        partial void OnCodi_PostalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Població
        {
            get
            {
                return _Població;
            }
            set
            {
                OnPoblacióChanging(value);
                ReportPropertyChanging("Població");
                _Població = StructuralObject.SetValidValue(value, false, "Població");
                ReportPropertyChanged("Població");
                OnPoblacióChanged();
            }
        }
        private global::System.String _Població;
        partial void OnPoblacióChanging(global::System.String value);
        partial void OnPoblacióChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Província
        {
            get
            {
                return _Província;
            }
            set
            {
                OnProvínciaChanging(value);
                ReportPropertyChanging("Província");
                _Província = StructuralObject.SetValidValue(value, false, "Província");
                ReportPropertyChanged("Província");
                OnProvínciaChanged();
            }
        }
        private global::System.String _Província;
        partial void OnProvínciaChanging(global::System.String value);
        partial void OnProvínciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Telèfon
        {
            get
            {
                return _Telèfon;
            }
            set
            {
                OnTelèfonChanging(value);
                ReportPropertyChanging("Telèfon");
                _Telèfon = StructuralObject.SetValidValue(value, "Telèfon");
                ReportPropertyChanged("Telèfon");
                OnTelèfonChanged();
            }
        }
        private Nullable<global::System.Int32> _Telèfon;
        partial void OnTelèfonChanging(Nullable<global::System.Int32> value);
        partial void OnTelèfonChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, "Fax");
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private Nullable<global::System.Int32> _Fax;
        partial void OnFaxChanging(Nullable<global::System.Int32> value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("practicam6Model", "factura_ibfk_1", "factura")]
        public EntityCollection<factura> factura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factura>("practicam6Model.factura_ibfk_1", "factura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factura>("practicam6Model.factura_ibfk_1", "factura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="practicam6Model", Name="factura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class factura : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto factura.
        /// </summary>
        /// <param name="n_Factura">Valor inicial de la propiedad n_Factura.</param>
        public static factura Createfactura(global::System.Int32 n_Factura)
        {
            factura factura = new factura();
            factura.n_Factura = n_Factura;
            return factura;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 n_Factura
        {
            get
            {
                return _n_Factura;
            }
            set
            {
                if (_n_Factura != value)
                {
                    Onn_FacturaChanging(value);
                    ReportPropertyChanging("n_Factura");
                    _n_Factura = StructuralObject.SetValidValue(value, "n_Factura");
                    ReportPropertyChanged("n_Factura");
                    Onn_FacturaChanged();
                }
            }
        }
        private global::System.Int32 _n_Factura;
        partial void Onn_FacturaChanging(global::System.Int32 value);
        partial void Onn_FacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_Client
        {
            get
            {
                return _id_Client;
            }
            set
            {
                Onid_ClientChanging(value);
                ReportPropertyChanging("id_Client");
                _id_Client = StructuralObject.SetValidValue(value, "id_Client");
                ReportPropertyChanged("id_Client");
                Onid_ClientChanged();
            }
        }
        private Nullable<global::System.Int32> _id_Client;
        partial void Onid_ClientChanging(Nullable<global::System.Int32> value);
        partial void Onid_ClientChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, "Data");
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Descompte
        {
            get
            {
                return _Descompte;
            }
            set
            {
                OnDescompteChanging(value);
                ReportPropertyChanging("Descompte");
                _Descompte = StructuralObject.SetValidValue(value, "Descompte");
                ReportPropertyChanged("Descompte");
                OnDescompteChanged();
            }
        }
        private Nullable<global::System.Int32> _Descompte;
        partial void OnDescompteChanging(Nullable<global::System.Int32> value);
        partial void OnDescompteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IVA
        {
            get
            {
                return _IVA;
            }
            set
            {
                OnIVAChanging(value);
                ReportPropertyChanging("IVA");
                _IVA = StructuralObject.SetValidValue(value, "IVA");
                ReportPropertyChanged("IVA");
                OnIVAChanged();
            }
        }
        private Nullable<global::System.Int32> _IVA;
        partial void OnIVAChanging(Nullable<global::System.Int32> value);
        partial void OnIVAChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("practicam6Model", "factura_ibfk_1", "clients")]
        public clients clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clients>("practicam6Model.factura_ibfk_1", "clients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clients>("practicam6Model.factura_ibfk_1", "clients").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clients> clientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clients>("practicam6Model.factura_ibfk_1", "clients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clients>("practicam6Model.factura_ibfk_1", "clients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="practicam6Model", Name="factura_detall")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class factura_detall : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto factura_detall.
        /// </summary>
        /// <param name="n_Factura">Valor inicial de la propiedad n_Factura.</param>
        /// <param name="id_Producte">Valor inicial de la propiedad id_Producte.</param>
        public static factura_detall Createfactura_detall(global::System.Int32 n_Factura, global::System.Int32 id_Producte)
        {
            factura_detall factura_detall = new factura_detall();
            factura_detall.n_Factura = n_Factura;
            factura_detall.id_Producte = id_Producte;
            return factura_detall;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 n_Factura
        {
            get
            {
                return _n_Factura;
            }
            set
            {
                if (_n_Factura != value)
                {
                    Onn_FacturaChanging(value);
                    ReportPropertyChanging("n_Factura");
                    _n_Factura = StructuralObject.SetValidValue(value, "n_Factura");
                    ReportPropertyChanged("n_Factura");
                    Onn_FacturaChanged();
                }
            }
        }
        private global::System.Int32 _n_Factura;
        partial void Onn_FacturaChanging(global::System.Int32 value);
        partial void Onn_FacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Producte
        {
            get
            {
                return _id_Producte;
            }
            set
            {
                if (_id_Producte != value)
                {
                    Onid_ProducteChanging(value);
                    ReportPropertyChanging("id_Producte");
                    _id_Producte = StructuralObject.SetValidValue(value, "id_Producte");
                    ReportPropertyChanged("id_Producte");
                    Onid_ProducteChanged();
                }
            }
        }
        private global::System.Int32 _id_Producte;
        partial void Onid_ProducteChanging(global::System.Int32 value);
        partial void Onid_ProducteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantitat
        {
            get
            {
                return _Quantitat;
            }
            set
            {
                OnQuantitatChanging(value);
                ReportPropertyChanging("Quantitat");
                _Quantitat = StructuralObject.SetValidValue(value, "Quantitat");
                ReportPropertyChanged("Quantitat");
                OnQuantitatChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantitat;
        partial void OnQuantitatChanging(Nullable<global::System.Int32> value);
        partial void OnQuantitatChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="practicam6Model", Name="productes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class productes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto productes.
        /// </summary>
        /// <param name="id_Producte">Valor inicial de la propiedad id_Producte.</param>
        public static productes Createproductes(global::System.Int32 id_Producte)
        {
            productes productes = new productes();
            productes.id_Producte = id_Producte;
            return productes;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Producte
        {
            get
            {
                return _id_Producte;
            }
            set
            {
                if (_id_Producte != value)
                {
                    Onid_ProducteChanging(value);
                    ReportPropertyChanging("id_Producte");
                    _id_Producte = StructuralObject.SetValidValue(value, "id_Producte");
                    ReportPropertyChanged("id_Producte");
                    Onid_ProducteChanged();
                }
            }
        }
        private global::System.Int32 _id_Producte;
        partial void Onid_ProducteChanging(global::System.Int32 value);
        partial void Onid_ProducteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producte
        {
            get
            {
                return _Producte;
            }
            set
            {
                OnProducteChanging(value);
                ReportPropertyChanging("Producte");
                _Producte = StructuralObject.SetValidValue(value, true, "Producte");
                ReportPropertyChanged("Producte");
                OnProducteChanged();
            }
        }
        private global::System.String _Producte;
        partial void OnProducteChanging(global::System.String value);
        partial void OnProducteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Preu
        {
            get
            {
                return _Preu;
            }
            set
            {
                OnPreuChanging(value);
                ReportPropertyChanging("Preu");
                _Preu = StructuralObject.SetValidValue(value, "Preu");
                ReportPropertyChanged("Preu");
                OnPreuChanged();
            }
        }
        private Nullable<global::System.Decimal> _Preu;
        partial void OnPreuChanging(Nullable<global::System.Decimal> value);
        partial void OnPreuChanged();

        #endregion

    }

    #endregion

}
